apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: arsenteroganisyan/order-service:v113

        ports:
        - containerPort: 8000
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_db_port
          - name: HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_db_host
          - name: USER
            valueFrom:
              secretKeyRef:
                name: secret
                key: order_db_user
          - name: DB
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_db
          - name: PASSWRORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: order_db_password
          - name: SESSION_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_session_host
          - name: PAYMENT_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_payment_host
          - name: DELIVERY_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_delivery_host
          - name: STOCK_HOST
            valueFrom:
              configMapKeyRef:
                name: config
                key: order_stock_host